version: '3.8'

services:
  wagy-webapp:
    build:
      context: .
      args:
        # Pass the API URL to the Dockerfile as a build argument
        - REACT_APP_API_URL=https://petapi.gp24.ir
    container_name: wagy-webapp-container
    ports:
      - "8080:80"
    restart: unless-stopped
